highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://mingmingdiii.online/

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: 董明辉的个人简历
name: 董明辉
email: dmh_hust@126.com
email_full: dmh_hust@126.com
website: http://mingmingdiii.online/
website_full: http://mingmingdiii.online/
github: trending
twitter: twitter
tel: 17798263772
tel_full: tel:+86 17798263772
google_maps: 'http://mingmingdiii.online/'
address:
  street: hust
  postcode: hust
  city: hust
  country: hust
google_analytics: hust

# needed for travis-ci build
exclude: [vendor]
