highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://mingmingdiii.online/


baseurl: /
title: 董明辉的个人主页
name: 董明辉
email: dmh_hust@126.com
website: mingmingdiii.online
github: mingmingdiii
kaggle: mingmingdiii
tel: 17798263772
address:
  street: 华中科技大学
  city: 武汉
  country: 中国
# needed for travis-ci build
#exclude: [vendor]
